# Generated by Django 6.0.7 on 2026-07-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email_address', models.EmailField(max_length=254)),
                ('issue_subject', models.CharField(max_length=200)),
                ('detailed_message', models.TextField()),
                ('urgency_level', models.CharField(choices=[('LOW', 'General Inquiry'), ('HIGH', 'Urgent Issue')], default='LOW', max_length=4)),
                ('submitted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
